services:
  - type: worker
    name: okx-trailing-bot
    env: python
    plan: free
    buildCommand: pip install -r requisitos.txt
    startCommand: python main.py
    branch: main
    autoDeploy: true
    envVars:
      - key: OKX_API_KEY
        sync: false
      - key: OKX_API_SECRET
        sync: false
      - key: OKX_PASSPHRASE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CALLBACK_DELTA
        sync: false